apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes-custom
spec:
  type: NodePort
  selector:
    app: hello-kubernetes-custom
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
