steps:
  - task: KubernetesManifest@0
    displayName: Deploy
    inputs:
      kubernetesServiceConnection: someK8sSC1
      namespace: default
      manifests: |
        manifests/deployment.yml
        manifests/service.yml
      containers: |
        foo/demo:$(tagVariable1)
        bar/demo:$(tagVariable2)
      imagePullSecrets: |
        some-secret
        some-other-secret
