name: Hello Kubernetes CI Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CONTAINER_REGISTRY: demoregistrry.azurecr.io
  image_name: hello-kubernetes
  image_version: 1.7
jobs:
  build_app_image:
    environment: demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          # Container registry username
          username: ${{ secrets.ACR_USERNAME }}
          # Container registry password
          password: ${{ secrets.ACR_PASSWORD }}
          # Container registry server url
          login-server: ${{env.CONTAINER_REGISTRY}}

      - name: Build and Push  Docker image
        run: |
          docker build app \
            --file Dockerfile \
            --tag ${{env.image_name}}:${{env.image_version}} \
            --build-arg IMAGE_VERSION=${{env.image_version}} \
            --build-arg IMAGE_CREATE_DATE="`date -u +"%Y-%m-%dT%H:%M:%SZ"`" \
            --build-arg IMAGE_SOURCE_REVISION="`git rev-parse HEAD`"
          docker push ${{env.CONTAINER_REGISTRY}}/${{env.image_name}}:${{ env.image_version }}
